project:
  type: website

website:
  title: "Tarun Bathini"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/tarunbathini/
format:
  html:
    theme: dark
    css: styles.css

editor: visual

